# This is a basic workflow to help you get started with Actions

name: Simple Workflow

on:
  push

jobs:
  build:
    name: Hello World
    runs-on: [ubuntu-latest]
    steps:
      - name: Say hello using an action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Howest
        id: hello
        
      - name: Get output from hello action
        run: echo "The time is ${{ hello.outputs.time }}"
        
