# This is a basic workflow to help you get started with Actions

name: Simple Workflow

on:
  push
  

jobs:
  build:
    name: Hello World
    runs-on: [ubuntu-latest]
    steps:
      - name: Say hello using an action
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Howest
        id: hello
        
      - name: Set environment variables
        run: echo 'Hello $FIRST_NAME $last_name'
        env:
          FIRST_NAME: Nick
          last_name: Trogh    
